[package]
name = "mp4-macros"
version = "0.1.0"
edition = "2021"
authors = ["Shalom <ski0090@naver.com"]
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = "2"
